#!/usr/bin/env bash
# Scan assets/images/projects/ and write a manifest the admin image picker reads.
# Run after adding, moving, or converting project media:  ./scripts/build-portfolio-assets.sh
#
# Exists because the picker used to read hardcoded path lists that went stale the
# moment any file was renamed or moved.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/assets/images/projects"
OUT="$ROOT/assets/js/portfolio-assets.js"

if [[ ! -d "$DIR" ]]; then
  echo "Missing $DIR" >&2
  exit 1
fi

python3 - "$DIR" "$OUT" <<'PY'
import json, os, sys

src, out = sys.argv[1], sys.argv[2]
IMG = {'.webp', '.png', '.jpg', '.jpeg', '.svg', '.gif'}
VID = {'.webm', '.mp4'}

groups = {}
for dirpath, dirnames, filenames in os.walk(src):
    dirnames[:] = [d for d in dirnames if not d.startswith('.')]
    for name in sorted(filenames):
        if name.startswith('.'):
            continue
        ext = os.path.splitext(name)[1].lower()
        if ext not in IMG and ext not in VID:
            continue
        rel = os.path.relpath(os.path.join(dirpath, name), src)
        group = os.path.dirname(rel) or 'general'
        stem = os.path.splitext(name)[0]
        # A *-poster.webp is a video thumbnail, not a slide in its own right.
        if stem.endswith('-poster'):
            continue
        entry = {
            'path': '/assets/images/projects/' + rel.replace(os.sep, '/'),
            'name': name,
            'kind': 'video' if ext in VID else 'image',
        }
        if ext in VID:
            poster = os.path.join(dirpath, stem + '-poster.webp')
            if os.path.isfile(poster):
                entry['poster'] = '/assets/images/projects/' + os.path.relpath(
                    poster, src).replace(os.sep, '/')
        groups.setdefault(group, []).append(entry)

payload = [{'group': g, 'files': groups[g]} for g in sorted(groups)]
total = sum(len(g['files']) for g in payload)

with open(out, 'w', encoding='utf-8') as fh:
    fh.write('/* GENERATED by scripts/build-portfolio-assets.sh — do not edit by hand. */\n')
    fh.write('/* Re-run that script whenever project media is added, moved, or renamed. */\n')
    fh.write('window.PORTFOLIO_ASSET_GROUPS = ')
    json.dump(payload, fh, indent=2)
    fh.write(';\n\n')
    fh.write('window.PORTFOLIO_ASSET_IMAGES = window.PORTFOLIO_ASSET_GROUPS.reduce(\n')
    fh.write('  function (acc, g) { return acc.concat(g.files.map(function (f) { return f.path; })); },\n')
    fh.write('  []\n);\n')

print('wrote %s — %d groups, %d files' % (os.path.relpath(out, os.path.dirname(os.path.dirname(out))), len(payload), total))
PY
