#!/usr/bin/env bash
# Scan project media and write a manifest the admin image picker reads.
# Run after adding, moving, or converting project media:  ./scripts/build-portfolio-assets.sh
#
# Sources:
#   assets/images/projects/<folder>/...   → one group per folder (slideshow media)
#   assets/docs/projects/<project>/...    → one group per project (guide screenshots)
#
# Exists because the picker used to read hardcoded path lists that went stale the
# moment any file was renamed or moved.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/assets/images/projects"
DOCS="$ROOT/assets/docs/projects"
OUT="$ROOT/assets/js/portfolio-assets.js"

if [[ ! -d "$DIR" ]]; then
  echo "Missing $DIR" >&2
  exit 1
fi

python3 - "$DIR" "$DOCS" "$OUT" <<'PY'
import json, os, sys

src, docs, out = sys.argv[1], sys.argv[2], sys.argv[3]
IMG = {'.webp', '.png', '.jpg', '.jpeg', '.svg', '.gif'}
VID = {'.webm', '.mp4'}


def walk(base, url_prefix, group_for):
    """Yield (group, folder, entry) for every media file under base."""
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith('.'))
        for name in sorted(filenames):
            if name.startswith('.'):
                continue
            ext = os.path.splitext(name)[1].lower()
            if ext not in IMG and ext not in VID:
                continue
            stem = os.path.splitext(name)[0]
            # A *-poster.webp is a video thumbnail, not a slide in its own right.
            if stem.endswith('-poster'):
                continue
            rel = os.path.relpath(os.path.join(dirpath, name), base).replace(os.sep, '/')
            grouped = group_for(rel)
            if not grouped:
                continue
            group, folder = grouped
            entry = {
                'path': url_prefix + rel,
                'name': name,
                'kind': 'video' if ext in VID else 'image',
            }
            if folder:
                entry['folder'] = folder
            if ext in VID:
                poster = os.path.join(dirpath, stem + '-poster.webp')
                if os.path.isfile(poster):
                    entry['poster'] = url_prefix + os.path.relpath(poster, base).replace(os.sep, '/')
            yield group, entry


def images_group(rel):
    return (os.path.dirname(rel) or 'general', '')


def docs_group(rel):
    parts = rel.split('/')
    if len(parts) < 2:
        return None
    return ('docs/' + parts[0], '/'.join(parts[1:-1]))


groups = {}
labels = {}
sources = {}
for group, entry in walk(src, '/assets/images/projects/', images_group):
    groups.setdefault(group, []).append(entry)
    labels[group] = group
    sources[group] = 'images'

if os.path.isdir(docs):
    for group, entry in walk(docs, '/assets/docs/projects/', docs_group):
        groups.setdefault(group, []).append(entry)
        labels[group] = group[len('docs/'):] + ' — guide screenshots'
        sources[group] = 'docs'

for files in groups.values():
    files.sort(key=lambda f: (f.get('folder', ''), f['name']))

# Slideshow folders first, guide screenshots after.
order = sorted(groups, key=lambda g: (sources[g] != 'images', g))
payload = [
    {'group': g, 'label': labels[g], 'source': sources[g], 'files': groups[g]}
    for g in order
]
total = sum(len(g['files']) for g in payload)

with open(out, 'w', encoding='utf-8') as fh:
    fh.write('/* GENERATED by scripts/build-portfolio-assets.sh — do not edit by hand. */\n')
    fh.write('/* Re-run that script whenever project media is added, moved, or renamed. */\n')
    fh.write('window.PORTFOLIO_ASSET_GROUPS = ')
    json.dump(payload, fh, indent=2, ensure_ascii=False)
    fh.write(';\n\n')
    fh.write('window.PORTFOLIO_ASSET_IMAGES = window.PORTFOLIO_ASSET_GROUPS.reduce(\n')
    fh.write('  function (acc, g) { return acc.concat(g.files.map(function (f) { return f.path; })); },\n')
    fh.write('  []\n);\n')

print('wrote %s — %d groups, %d files' % (os.path.relpath(out, os.path.dirname(os.path.dirname(out))), len(payload), total))
PY
